### ISSUE TITLE
Missing dependencys

### ISSUE THREAD

**Issue by n0o0ne** [MrJohnZoidberg/Snips-Wecker#8]
OS: Raspbian stretch lite

The command is recognised. domi:newAlarm or domi:geAlarms is recognised but then i get the error:"The session was ended because one of the component didn't respond in a timely manner"

I figured out the following dependencys are missing:
- paho-mqtt -> installer said it installed it, but after executing the action-domi-wecker.py the errors said import paho.mqtt.client as mqtt ImportError No module named paho.mqtt.client. pip install paho-mqtt solved the problem.
- pydub -> pip install pydub
- alarmclock.py wanted ffmpeg or avconv -> apt-get install ffmpeg

sadly i still get the "...didn't respond in a timely manner" error.

**Comment by dominiczedler** [comment]
You have to install this app with SAM, or you have to execute the setup.sh with the user "_snips-skills", because this creates a virtual environment where the packages are installed to.

[https://docs.snips.ai/getting-started/quick-start-raspberry-pi](https://docs.snips.ai/getting-started/quick-start-raspberry-pi)
